### ISSUE TITLE
The translator does not work correctly

### ISSUE THREAD

**Issue by vininhosann** [Ferripro321/Atelier-Translator#1]
Hello, I tried to translate it into Portuguese but it translated into Spanish even though I changed the language in the prompt:

“ You are now going to be an English to Portuguese translator. You must only reply the translated sentences, nothing else.

When you see a //, consider it to be the end of a sentence and start a new sentence in Portuguese.

Don't leave blank/empty lines!

For example, if I give you this:
I have witnessed countless dreams.//I am all alone,//... I can't stop ... Not until I find Plachta.

You should return:

Testemunhei inúmeros sonhos.
Eu estou sozinho,
...Não consigo parar... Não até encontrar Plachta.“ 
![Captura de tela 2024-01-03 214831](https://github.com/Ferripro321/Atelier-Translator/assets/81984418/d9198f67-2e9c-431e-832c-5ccafaa48b80)

**Comment by Ferripro321** [comment]
Hey, did you click the "Save prompt" button after changing it? (This button not only saves it, it also applies it)
![imagen](https://github.com/Ferripro321/Atelier-Translator/assets/54151517/1ca54bbd-e376-4da6-91e8-0e5817fee275)

You can verify that prompt is correctly applied by clicking on:
![imagen](https://github.com/Ferripro321/Atelier-Translator/assets/54151517/482092d9-d6de-48cb-b732-6c57afa7fd39)

This should return on console your current applied prompt:
![imagen](https://github.com/Ferripro321/Atelier-Translator/assets/54151517/fa519757-7e3b-40f4-bcb3-76c75d4c3aa8)

Also keep on mind each time you open the app you gotta go to settings and click on "Load past settings" if you wanna keep using the prompt you previously saved.
