### ISSUE TITLE
Question for the translation 

### ISSUE THREAD

**Issue by lolkingfire19** [Ferripro321/Atelier-Translator#2]
The question tha im asking is it normal that the completed translation files are in Spanish and not in the language I chose? Now I'm trying to translate atelier ryza 3 and It take time so im here to ask if Is normal so i dont Need redo again all things im sure use correct protom
Sorry for my bad english

**Comment by Ferripro321** [comment]
Ok, yes, this is a known issue, I was too lazy to fix it.

Here is a workaround for now:
Go into the functions.py file and edit the prompt there. After that, save the file and reopen the translation.
![Screenshot_1](https://github.com/Ferripro321/Atelier-Translator/assets/54151517/b187a619-a2ab-4f20-b936-11dfb9ba35c3)
_Image of the code you must edit to change the prompt_

Sorry for this issue and I might fix it next week.

**Comment by Ferripro321** [comment]
Ups, I closed it by accident

**Comment by lolkingfire19** [comment]
How do I know when the translation is finished and it says 76/76 finished translation skipping.... i Need wait?

**Comment by Ferripro321** [comment]
> How do I know when the translation is finished and it says 76/76 finished translation skipping.... i Need wait?

Could you send a screenshot so I can understand better what you are telling me, thanks.

**Comment by lolkingfire19** [comment]
![Screenshot 2024-03-13 102239](https://github.com/Ferripro321/Atelier-Translator/assets/102462217/4513e209-6491-4316-b34f-ffaee306fedc)

**Comment by Ferripro321** [comment]
If the tool stopped and it's not doing anything then probably it did finish, if you don't know how to continue I would recommend you to check my video on youtube about this tool: https://youtu.be/mfFFQcsyOAI?si=5OMFbkUyA4MnvhCh
If you have any other doubt and want a faster reply you can message me on discord: ferripro

Edit: closed as this is not an issue, it's more of a support ticket, so I can help you on discord but this is probably not the best place for this
